#!/usr/bin/env python
import argparse
from installer.constants.ascii import ASCII_ART
from installer.registries import (
    TARGET_REGISTRY,
    OPTION_REGISTRY,
    register_targets,
)


# ====
# MAIN
# ====

# register the installation targets on the registry.
register_targets()

# define a command parser
parser = argparse.ArgumentParser('cli for dotfile installation')
parser.add_argument('target', choices=[
    t for t in TARGET_REGISTRY.keys() if not t.startswith('_')
])
parser.add_argument(
    '--assume-no-sudo-authority', action='store_false', dest='sudo'
)


if __name__ == '__main__':
    print(ASCII_ART)
    args = parser.parse_args()
    OPTION_REGISTRY.update(args.__dict__)
    TARGET_REGISTRY[args.target]()
